### ISSUE TITLE
Any release soon?

### ISSUE THREAD

**Issue by FerdinandoPH** [joeldipops/TransferBoy#46]
I tried to compile it, but installing libdragon and a toolchain was too hard for me. I would love to try this though, so I was wondering if binaries are planed to be released anytime soon.

**Comment by joeldipops** [comment]
Thanks for giving it a go.
I actually check the latest built ROM in whenever I commit.
https://github.com/joeldipops/TransferBoy/blob/master/transferboy.z64

This is naturally very unstable of course, but enough to have a look. 
I'm no-where near close to a proper 'release' because performance issues make most games either unplayable or a very slow-mo experience.


The ROM in this branch may be slightly better
https://github.com/joeldipops/TransferBoy/blob/op_hand_optimisation/transferboy.z64

**Comment by FerdinandoPH** [comment]
Thanks for the rom. I already supposed that this was stable yet, but I find this project very interesting!
